robchahin/sso-wall-of-shame

- index.md
I'm not sure what to put for pricing. They don't actually give you straight pricing, they have this estimator tool. But it's about 2x whatever you're paying for "Essentials"
> Add NewRelic

- assets/css/style.scss
- index.md
Without this, the Source column will wrap if "Quote" is added, and the Date Added column will wrap if a footnote is added.
> Don't wrap Source or Date Added columns

- index.md
Adds closing bracket to the Sumologic link
> Fix Sumologic

- _data/vendors.yml
- index.md
Separates the data from the presentation.
> Move vendors to data file

- _data/vendors.yml
- index.md
Created a branch to make non-prod footnote addition to index.md
> Merge Twilio branch after footnote addition

- _data/vendors.yml
- index.md
Keeps all the vendor data together.
> Move footnotes into data file

- _data/vendors.yml
If you're accepting new submissions, just added a couple that I thought were relevant.
OpsGenie and PagerTree.
> Added PagerTree & OpsGenie to vendors.yml

- _data/vendors.yml
https://www.smartsheet.com/pricing
SSO gated behind their Enterprise or Premier pricing levels.
> Add Smartsheet

- _data/vendors.yml
SAML only supported on [Enterprise plan](https://help.dialpad.com/hc/en-us/articles/115003085466-G-Suite-Single-Sign-On-via-SAML).
> Add Dialpad

- _data/vendors.yml
$10 /u/m is the incremental price over the intro $30 <= 5 users package
> Add Quip pricing

- _data/vendors.yml
> add Checkly

- _data/vendors.yml
> Update vendors.yml w/ copper crm pricing

- _data/vendors.yml
nothing fancy, just added Figma
> added Figma

- _data/vendors.yml
https://www.postman.com/pricing
> Add Details for Postman

- _data/vendors.yml
Added Squadcast to the vendor list.
> add Squadcast to vendors.yml

- _data/vendors.yml
Priced per location, SAML requires Premium tier (see 'Security and compliance' section of feature comparison.
> Added Envoy

- _data/vendors.yml
See https://www.pagerduty.com/pricing/
> As of 2020-09-21, PagerDuty is including SSO in all paid plans.

- _data/vendors.yml
Elasticsearch only offer SSO as part of their paid Platinum and Enterprise plans - https://www.elastic.co/subscriptions
> Add Elasticsearch

- _data/vendors.yml
Added monday.com based on recent negotiations.
> Added monday.com

- _data/vendors.yml
> Add TestRail Cloud

- _data/vendors.yml
Added Cloudflare with Pricing based on quote.
> Added Cloudflare

- _data/vendors.yml
Adding Clockify, not much more to say.
> Add Clockify

- _data/vendors.yml
Quote is a year old from 2020-10-16, but the pricing on their website hasn't changed.
> Added PandaDoc

- _data/vendors.yml
> Added Mural

- _data/vendors.yml
Not too sure about `per project/mo`
> Add ReadMe

- _data/vendors.yml
> Added Canva

- _data/vendors.yml
Got a quote from Zeplin that blew my mind.
> added zeplin

- _vendors/projectmanager.yaml
Project Manager has "Call Us" pricing for Enterprise.
$45 is the price that was quoted to me after a "10% discount", down from $50 per license/month
.
> Add Project Manager

- _vendors/calendly.yaml
Added Calendly data from quote received. This solves for Issue #278
> Added Calendly

- _vendors/retrium.yaml
Adds Retrium pricing from https://www.retrium.com/pricing
> Add Retrium

- _vendors/linear.yaml
> Added Linear

- _vendors/smartsheet.yaml
- index.md
Looking forward to some weird merge conflict I have somehow created.
> Merge FAQ with Call Us table

- CONTRIBUTING.md
- _vendors/gathercontent.yaml
Adding GatherContent as a vendor; updating guidelines for contributing Call Us vendors
> Adding vendor and updating guidelines

- _vendors/front.yaml
> Adding Front to the SSO Issues list

- _vendors/getresponse.yaml
- _vendors/sender.yaml
- _vendors/sendinblue.yaml
> WIP: Add email marketing providers

- _vendors/lucidchart.yaml
Implements quotes from https://github.com/robchahin/sso-wall-of-shame/pull/198
> Add lucidchart quote

- _vendors/docker.yaml
Updated pricing per Docker website, added direct link to pricing
> Add new Docker pricing

- _vendors/coursera.yaml
Another glorious vendor added to the "Call Us!" table.
https://www.coursera.org/business/compare-plans
> Added Coursera

- _vendors/logrocket.yaml
about: PR is filled with _vendor yaml.
What is the vendor's name?
LogRocket
What is the vendor's pricing site?
https://logrocket.com/pricing
What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.
$99 / month for up to 5 users
What is the minimum pricing for SSO support?
$500 / month plus $20 per seat
Does this pricing info come from a quote or other non-public source?
N/A
> Added LogRocket

- _vendors/prismic.yaml
> vendors: add Prismic

- _vendors/teamworkcom.yaml
> vendors: add Teamwork.com

- _vendors/pluralsight.yaml
> vendors: add Pluralsight

- _vendors/browserstack.yaml
> vendors: Add BrowserStack

- _vendors/saucelabs.yaml
> vendors: add Sauce Labs

- _vendors/metabase.yaml
> Add Metabase

- _vendors/workable.yaml
> Add Workable

- _vendors/projectdiscovery.yaml
---
name: ProjectDiscovery
about: I'd like to add a vendor
---
Please find this addition. Do let me know if I need to make any changes.
> Added projectdiscovery.io

- _vendors/intercom.yaml
Updating to current prices - they're going the wrong way.
> Intercom's price delta has gotten worse

- _vendors/bitwarden.yaml
4->6 is 50%, wasn't updated when the prices got updated
> Update bitwarden percentage

- _vendors/linearb.yaml
> Adding LinearB

- _vendors/typeform.yaml
Typeform requires Enterprise licensing for SSO. 
https://www.typeform.com/pricing/
> Add typeform.yaml

- _vendors/mailgun.yaml
> add mailgun

- _vendors/islonline.yaml
> Added ISL Online

- _vendors/playlister
Playlister recently introduced SSO... at their top pricing tier.  So, propose adding them here.
> Add playlister

- _vendors/stackhawk.yaml
> add StackHawk
