robchahin/sso-wall-of-shame

assets/css/style.scss, index.md
This makes the New Relic entry use a footnote instead of an element title, providing a template for future footnotes, and updates the pricing to be more accurate.
Depends on #8.
=> Improve New Relic

_data/vendors.yml
Wasn't quite sure how to capture the base pricing since it's PAYG,
but the Enterprise plan is clearly labeled as the _greater_ of $15k/mo
or 30% of monthly spend.
=> Add Twilio for their 30% surcharge Enterprise Plan

_data/vendors.yml
It looks like they changed their pricing at some point. The base version is now $5, the cheapest version w/ SSO is $11.
=> Update Stack Overflow's listing

_data/vendors.yml
Removing Dialpad per an e-mail from a user. The pricing was outdated, and all of their plans offer some form of SSO; but SAML isn't supported until the highest tier. It's not ideal but the nuance is hard to reflect in this format so it seems fairer to remove them from the list for now.
=> Remove dialpad

_data/vendors.yml
This change add Zapier pricing where the base is for teams rather than for individuals.
=> Add Zapier w/ base pricing for teams

_data/vendors.yml
Proposing to remove Zendesk from this document as we just made SSO inclusive on all plans. More information at https://support.zendesk.com/hc/en-us/articles/360037530914-Announcing-enhanced-product-security-features-for-all-plan-levels.
=> Update to remove Zendesk Support, SSO is now included with all plans

_data/vendors.yml
GitHub made a pricing change today, but unfortunately they didn't change how SAML is offered. So it's still part of Enterprise (now available self-serve for $21/u/m). This makes the percent increase 525%!
https://github.blog/2020-04-14-github-is-now-free-for-teams/
=> Update GitHub base pricing

_data/vendors.yml
Hey @robchahin! Joe from Customer.io's Site Reliability team here. Great project and thanks for taking the time to maintain this listing. Our team recently made the decision to remove the "premium" requirement on our SSO features and have made SSO available to all subscribers regardless of plan pricing. Here's a recent diff of [our documentation](https://customer.io/docs/login-with-sso) where we've removed the "you must be this premium to ride this ride" callout:
Previously when SSO was a Premium only feature our product team would enable it for any account that wrote in requesting it, but we realized this hurt overall discoverability/adoption of a core security feature so we've reversed course and turned SSO on by default for all accounts.
I believe this PR is sufficient to reverse …
=> remove customer.io, SSO is now available for all accounts

_data/vendors.yml
Since SSO appears to be included as a basic feature for the on-prem version of GitLab, it doesn't seem like it belongs on this list.  Additionally, according the the GitLab feature list, it's not actually SSO but ldap sync and auth.  Which does accomplish some of the same goals but does not provide the same user experience as true SSO.
=> Remove GitLab on-prem

_data/vendors.yml
It took me 2 years but I finally convinced them to move it into the standard tiers of pricing. The only tier that does not support it is free tier at 500mb but I think thats a fair stance to take if you are ingesting less than 500mb a day you likely dont have a team which is why SSO is kinda a baseline requirement for orgs.
https://www.sumologic.com/pricing/
Signed-off-by: Ben Abrams <me@benabrams.it>
=> remove sumo logic as they have seen the light

_data/vendors.yml
redash.io is a query editor for many types of data sources, and while they do offer a [self-hosted solution that allows SSO for free](https://redash.io/help/open-source/setup#Google-OAuth-Setup), their SaaS option has a 900% markup to enable SSO, as found in their "Business" plan.
=> Updated vendors, added redash.io

_data/vendors.yml
wDatabricks currently offers the ability for any customer to configure their own SAML SSO provider, with OIDC support coming soon.
There is no additional charge for doing this. See that the "SSO" option is default on all pricing tiers here:
https://databricks.com/product/aws-pricing
=> Removing Databricks from the sso.tax list

_data/vendors.yml
See https://stackoverflow.com/teams/pricing
=> Remove Stack Overflow, all paid tiers include SSO now.

_data/vendors.yml
For the same reasons Dialpad was [removed](https://github.com/robchahin/sso-wall-of-shame/commit/cd226d37b4b3486d4562be3aa4256f29ad4b74ca), Checkly should also be removed. SSO is offered at all tiers, but only the enterprise tier has SAML.
=> Remove Checkly.

_data/vendors.yml
Gitlab restructured from three to two tiers. Their current lowest tier (formerly their middle tier) includes SSO.
=> Remove gitlab

_vendors/grammarly.yaml
Grammarly's business plans start at $12.5/month, however require 50 or more users for SSO. This results in a price hike of over 5200%!
=> Add Grammarly

_vendors/docker.yaml
The grace period for Docker Desktop expires January 31, 2022 and SSO is only included in the highest pricing tier.
=> Add docker

_vendors/mailtrap.yaml
Adds Mailtrap, pricing from: https://mailtrap.io/pricing/
Chose the cheapest paid plan for the base price, please shout if that's the wrong way to do it
=> Add Mailtrap

_vendors/aqua.yaml
The history of Aqua appearing on the list is here: https://github.com/robchahin/sso-wall-of-shame/pull/148
In a nutshell, Aqua acquired CloudSploit, which at the time, may have met the criteria for shaming.  However, the CloudSploit AuthN/AuthZ functionality has long since been depricated. 
Aqua offers two products:
- **On-premise software**:  This has included SSO included in every license since the inception of the company.
- **SaaS offering**: This has also always offered SSO at every license level since its inception, however, previous pricing description made it unclear, whether or not SSO was included (it always was).
Here's the pricing page today.  You'll see there's nothing to suggest that SSO is a licensed feature: https://www.aquasec.com/pricing/
If additional proof or details …
=> Remove Aqua as they offer SSO for all products at every tier.

_vendors/postman.yaml
from $24 to $49 per user/month (billed annually, of course).
=> postman raised their SSO prices

_vendors/dmarcian.yaml
SSO only available at the Enterprise tier
=> Add vendor (Dmarcian)

_vendors/balsamiq.yaml
---
name: Balsamiq Wireframes
about: PR is filled with _vendor yaml. I'm happy to adjust this to the $49 tier being the 'base' if we see fit.
---
**What is the vendor's name?**
Balsamiq Wireframes
**What is the vendor's pricing site?**
https://balsamiq.com/buy/#cloud
**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$9 / 2 projects / month
$49 / 20 projects / month
**What is the minimum pricing for SSO support?**
$199 / 200 projects /month
**Does this pricing info come from a quote or other non-public source?**
N/A
**Are there any caveats we should list in the footnotes?**
There are slight discounts for annual pricing. In our personal use of Balsamiq, we do not need more than 1 'project' of wireframes, though I …
=> add balsamiq

_config.yml
Trying to solve the issue of Google calling the canonical url for this site the github URL rather than the sso.tax URL
=> Update DNS in config

_vendors/datocms.yaml
DatoCMS offers an unlisted 'Interim' tier for 8K per year compared to 1.2K/year.
This includes SSO and audit logging.
=> feat(vendor): add datocms

_vendors/adobeacrobat.yaml, _vendors/adobecreativecloud.yaml
Adding the two most common Adobe licenses, Creative Cloud and Acrobat Pro.
=> Add vendor (Adobe #390)

_vendors/cypress.yaml
This PR will also close #239 (is in new format)
---
name: Cypress.io
about: PR is filled with _vendor yaml. Cypress.io has just increased their "Team" tier to match the same user count. Difference in tiers:
- Team
- $75 / month
- 50 Users
- 10,000 Tests
- Business
- $300 / month
- 50 Users
- 10,000 Tests
- Adds a handful of other features such as Spec Prioritization, Auto Cancellation, GitHub Enterprise & ​On-Prem GitLab
As you can see above, there is a 400% price increase for single sign on and features that should not cost extra in my opinion. 🤷‍♂️
=> add cypress.io

_vendors/quoter.yaml
Adding Quoter - using price for lowest business tier + SSO add-on as the SSO cost as it's less than the lowest tier that includes SSO.
=> Add Quoter per Issue 427

_vendors/jam.yaml
Jam is a browser extension that allows you to create the perfect bug report in just one click.  They recently had a story on Hacker News and [I encouraged them to provide SSO for all their plans](https://news.ycombinator.com/item?id=40327763).  
Here was their reply:
>Great feedback, thank you!
>
>Our philosophy on pricing is to try and only make what real companies who can pay need, and offer what individuals and hobbyists and small startups need for for free, so that’s why SSO ended up a paid feature. But it’s great feedback for us - thank you!
=> Add Jam to vendors

_vendors/balsamiq.yaml
Balsamiq's SSO tax is now only 56% (down from 306%) as of today
=> Updated Balsamiq pricing

_vendors/canva.yaml
In order to enable SSO/SCIM (only available on the Enterprise plan) 25 licenses must be purchased with one year in advance payment (yearly billing cycle).
The sales representative did not agree to reduce the number of licenses to purchase the Enterprise plan, citing current company policy.
=> Amend canva.yaml

_vendors/temporalcloud.yaml
Adding Temporal Cloud per their https://temporal.io/pricing page.
Bare-minimum pricing for use is $200 for the support fee. Adding SAML is an additional $200 per month.
Pricing based on the assumption of a business using a real IDP like Okta.
=> Add Temporal Cloud

_vendors/readme.yaml
Their Enterprise plan has gone up to $3000 and is still the only plan with SSO.
=> Update ReadMe pricing data

_vendors/lansweeper.yaml
SSO is now available on all paid Lansweeper plans.
=> Remove Lansweeper

_vendors/socialpilot.yaml
Social Pilot is a popular social media management application. They only allow SSO on "enterprise" plans which I've contacted them to ask about pricing and gotten nothing back.
=> add SocialPilot

_vendors/genetec.yaml
Their pricing is _per connection_ which can add up quickly on a building with lots of cameras. The SSO tax is per connection, not a flat extra. Brutal.
=> Add Genetec SaaS

_vendors/shortio.yaml
Short.io is a url shortening site that charges 186% extra to get SSO.
=> Add Short io
